# Generated by Django 3.2.8 on 2021-11-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/organization')),
                ('category', models.CharField(choices=[('BEAUTY', 'Красота'), ('HEALTH', 'Здоровье'), ('CAFE', 'Рестораны и кафе'), ('FUNNY', 'Развлечения'), ('STUDY', 'Обучение'), ('FITNESS', 'Фитнес'), ('CONCERT', 'Концерты'), ('AUTO', 'Авто'), ('CHILD', 'Дети'), ('TRAVEL', 'Путешествия'), ('GIFT', 'Подарки'), ('DIFFERENT', 'Разное')], default='DIFFERENT', max_length=20)),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(verbose_name='Время окончания акции')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon_generate.organization')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(verbose_name='Время окончания qrкода')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon_generate.organization')),
            ],
            options={
                'verbose_name': 'QRкод',
                'verbose_name_plural': 'QRкоды',
            },
        ),
    ]
