# Generated by Django 3.2.8 on 2021-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_generate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('BEAUTY', 'Красота'), ('HEALTH', 'Здоровье'), ('CAFE', 'Рестораны и кафе'), ('FUNNY', 'Развлечения'), ('STUDY', 'Обучение'), ('FITNESS', 'Фитнес'), ('CONCERT', 'Концерты'), ('AUTO', 'Авто'), ('CHILD', 'Дети'), ('TRAVEL', 'Путешествия'), ('GIFT', 'Подарки'), ('DIFFERENT', 'Разное')], default='DIFFERENT', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/organization'),
        ),
    ]
