# Generated by Django 3.2.8 on 2021-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_generate', '0003_alter_qrcode_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='pic',
        ),
    ]
