# Generated by Django 3.2.8 on 2021-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_generate', '0004_auto_20211102_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
