# Generated by Django 3.2.8 on 2021-11-03 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_generate', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='sub_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
